Experiment_name : TestRunv5
Execution_mode : train  # Possible values: train, eval
Env_id : Foosball-2v2-v0  # Possible values: Goalkeeper-v0, Foosball-v0, Foosball-2v2-v0, Foosball-4v4-v0
Algorithm : ppo  # Possible values: a2c, ddpg, dqn, ppo, sac, td3, ars, qrdqn, tqc, trpo, ppo_lstm