a2c:
  policy: MlpPolicy
  verbose: 0
  gamma: 0.99
  learning_rate: 7e-4

ddpg:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

dqn:
  policy: MlpPolicy
  verbose: 0
  gamma: 0.99

ppo:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.999
  policy_kwargs: dict(net_arch=dict(vf=[1024, 1024, 512], pi=[1024, 1024, 512]))
  device: mps

sac:
  # MultiInputPolicy when using HER
  policy : MlpPolicy
  verbose: 0
  gamma : 0.99

td3:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

ars:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

qrdqn:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

tqc:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

trpo:
  policy : MlpPolicy
  verbose: 0
  gamma: 0.99

ppo_lstm:
  policy : MlpLstmPolicy
  verbose: 0
  gamma: 0.99